/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author pc
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        open_file_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delete_file_btn = new javax.swing.JButton();
        add_file_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.setModel(new FileSystemModel(new File("D:\\")));
            jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTree1MouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(jTree1);

            open_file_btn.setText("Open File");
            open_file_btn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    open_file_btnActionPerformed(evt);
                }
            });

            jLabel1.setText("jLabel1");

            jLabel2.setText("jLabel1");

            delete_file_btn.setText("Delete File");
            delete_file_btn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    delete_file_btnActionPerformed(evt);
                }
            });

            add_file_btn.setText("Add File");
            add_file_btn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    add_file_btnActionPerformed(evt);
                }
            });

            jMenu1.setText("File");
            jMenuBar1.add(jMenu1);

            jMenu2.setText("Edit");
            jMenuBar1.add(jMenu2);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(open_file_btn)
                            .addGap(18, 18, 18)
                            .addComponent(delete_file_btn)
                            .addGap(18, 18, 18)
                            .addComponent(add_file_btn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)))
                    .addContainerGap(259, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 95, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(open_file_btn)
                        .addComponent(delete_file_btn)
                        .addComponent(add_file_btn))
                    .addGap(44, 44, 44)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        //Jtreevar= jTree1.getSelectionPaths().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
        Jtreevar= jTree1.getAnchorSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
        
        jLabel1.setText(Jtreevar);
        jLabel2.setText(jTree1.getAnchorSelectionPath().toString());
        
    }//GEN-LAST:event_jTree1MouseClicked

    private void open_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_file_btnActionPerformed
        // TODO add your handling code here:
        try{
                File Selection=new File(Jtreevar);
                if(Selection.exists()){
                    if(Desktop.isDesktopSupported()){
                        Desktop.getDesktop().open(Selection);
                    }else{
                          JOptionPane.showMessageDialog(this, "Awt Desk is not supported","Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                
                }else{
                    JOptionPane.showMessageDialog(this, "File does not exists ","Error",JOptionPane.INFORMATION_MESSAGE);
                }
            
            
        }catch (Exception ex){
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_open_file_btnActionPerformed

    private void delete_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_file_btnActionPerformed
        // TODO add your handling code here:
        try{
                File Selection=new File(Jtreevar);
               
                if(Selection.exists()){
                    if(Desktop.isDesktopSupported()){
                        File file = new File(Jtreevar);
                        file.delete();
                        //node1 = new DefaultMutableTreeNode(Jtreevar+"\\"+fOutput);
                        /*
                        newNode = new DefaultMutableTreeNode(fOutput);
                        newNode.setAllowsChildren(true);
                        //parentPath = jTree1.getAnchorSelectionPath();
                        parentPath = jTree1.getSelectionPath();
                        parentNode = (DefaultMutableTreeNode) (parentPath.getLastPathComponent());
                        treeModel.insertNodeInto(newNode, parentNode, parentNode
					.getChildCount());
                        jTree1.scrollPathToVisible(new TreePath(jTree1.getSelectionPath()));
                        */
                    }else{
                          JOptionPane.showMessageDialog(this, "Awt Desk is not supported","Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                    jTree1.setModel(new FileSystemModel(new File("D:\\")));
                }else{
                    JOptionPane.showMessageDialog(this, "File does not exists ","Error",JOptionPane.INFORMATION_MESSAGE);
                }
        }catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_delete_file_btnActionPerformed

    private void add_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_file_btnActionPerformed
        // TODO add your handling code here:
        try{
                File Selection=new File(Jtreevar);
                File tmp;
                DefaultMutableTreeNode node1=null,parentNode=null;
                DefaultTreeModel treeModel = null;
                DefaultMutableTreeNode newNode;
		TreePath parentPath;

                String fOutput = JOptionPane.showInputDialog(null, "請輸入檔案名稱及副檔名","確認", JOptionPane.OK_CANCEL_OPTION);
                
                if(Selection.exists()){
                    if(Desktop.isDesktopSupported()){
                        FileWriter file = new FileWriter(Jtreevar+"\\"+fOutput, false);
                        file.close();
                        //node1 = new DefaultMutableTreeNode(Jtreevar+"\\"+fOutput);
                        /*
                        newNode = new DefaultMutableTreeNode(fOutput);
                        newNode.setAllowsChildren(true);
                        //parentPath = jTree1.getAnchorSelectionPath();
                        parentPath = jTree1.getSelectionPath();
                        parentNode = (DefaultMutableTreeNode) (parentPath.getLastPathComponent());
                        treeModel.insertNodeInto(newNode, parentNode, parentNode
					.getChildCount());
                        jTree1.scrollPathToVisible(new TreePath(jTree1.getSelectionPath()));
                        */
                    }else{
                          JOptionPane.showMessageDialog(this, "Awt Desk is not supported","Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                    jTree1.setModel(new FileSystemModel(new File("D:\\")));
                }else{
                    JOptionPane.showMessageDialog(this, "File does not exists ","Error",JOptionPane.INFORMATION_MESSAGE);
                }
        }catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_file_btnActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_file_btn;
    private javax.swing.JButton delete_file_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton open_file_btn;
    // End of variables declaration//GEN-END:variables
    String Jtreevar;
}
